name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          register-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install -g npm
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Publish Package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
